FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

ENV LANG=C.UTF-8 \
    LANGUAGE=en_US \
    PYTHONPATH="/root/workspace:$PYTHONPATH" \
    POETRY_HOME="/opt/poetry" \
    PATH="/opt/poetry/bin:$PATH" \
    DEBIAN_FRONTEND=noninteractive

# Pythonのインストール
RUN apt-get update && apt-get install -y python3.10 python3-pip python3.10-venv \
    && ln -s /usr/bin/python3.10 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

# システム依存のライブラリをインストール
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/workspace

# Poetryのインストールと依存関係のインストール
RUN python3.10 -m venv $POETRY_HOME \
    && $POETRY_HOME/bin/pip install --upgrade pip \
    && $POETRY_HOME/bin/pip install poetry

# pyproject.toml、poetry.lock、poetry.tomlをコピーする
COPY pyproject.toml poetry.lock poetry.toml $WORKDIR/

RUN poetry install --no-root --no-dev

# Temporary directory for Poetry and torch installation
ENV TMPDIR=/root/workspace/tmp
RUN mkdir -p $TMPDIR

# OpenAI-Whisperに必要なライブラリをインストール
RUN apt-get update && apt-get install -y ffmpeg

# Clear cache to free up space
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
