version: "3.3"
services:
  test:
    build: .
    env_file:
      - .env.test
    volumes:
      - .:/root/workspace
    tty: true
    command: /bin/bash
    shm_size: 2gb
    depends_on:
      - ${MONGODB_HOST_NAME}
    networks:
      - default
    environment:
      - ENV=test

  mongodb:
    image: mongo:5.0.4
    env_file:
      - .env.test
    container_name: ${MONGODB_HOST_NAME}
    hostname: ${MONGODB_HOST_NAME}
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_USER_PWD}
      TZ: Asia/Tokyo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - default
    command: mongod --bind_ip_all --dbpath /data/db

networks:
  default:
    driver: bridge
