version: "3.3"
services:
  prod:
    build: .
    env_file:
      - .env.prod
    volumes:
      - .:/root/workspace
      - ${DATADRIVE}/db:/data/db
    tty: true
    command: /bin/bash
    shm_size: ${DOCKER_SHM_SIZE}
    ports:
      - "8000:8000"
    depends_on:
      - ${MONGODB_HOST_NAME}
    networks:
      - default
    environment:
      - ENV=prod

  mongodb:
    image: mongo:5.0.4
    env_file:
      - .env.prod
    container_name: ${MONGODB_HOST_NAME}
    hostname: ${MONGODB_HOST_NAME}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_USER_PWD}
      TZ: Asia/Tokyo
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ${DATADRIVE}/db:/data/db
    networks:
      - default
    command: mongod --bind_ip_all --dbpath /data/db

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_USER_PWD}
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_HOST_NAME}
    depends_on:
      - ${MONGODB_HOST_NAME}
    networks:
      - default

networks:
  default:
    driver: bridge
