version: "3.3"
services:
  prod:
    build: .
    volumes:
      - .:/root/workspace
    env_file:
      - .env
    tty: true # retain container up
    command: /bin/bash
    shm_size: $DOCKER_SHM_SIZE
    ports:
      - "8000:8000"
