version: "3.3"
services:
  test:
    build: .
    env_file:
      - .env.test
    volumes:
      - .:/root/workspace
      # - ${DATADRIVE}/db:/data/db
    tty: true
    command: /bin/bash
    shm_size: 2gb
    depends_on:
      # - ${MONGODB_HOST_NAME}
      - mongodb
    networks:
      - default
    environment:
      - ENV=test

  mongodb:
    image: mongo:5.0.4
    env_file:
      - .env.test
    # container_name: ${MONGODB_HOST_NAME}
    container_name: mongodb
    # hostname: ${MONGODB_HOST_NAME}
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_USER_PWD}
      TZ: Asia/Tokyo
    ports:
      - "27017:27017"
    # volumes:
    #   - ${DATADRIVE}/db:/db
    networks:
      - default
    command: mongod --bind_ip_all --dbpath db
    # command: /bin/bash

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env.test
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_USER_PWD}
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_HOST_NAME}
    depends_on:
      # - ${MONGODB_HOST_NAME}
      - mongodb
    networks:
      - default

networks:
  default:
    driver: bridge
