name: pytest

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - uses: actions/checkout@v3
      - name: create .env file
        run: |
          touch .env.test
          echo "APP_NAME=${{ vars.APP_NAME }}" > .env
          echo "API_VERSION=${{ vars.API_VERSION }}" >> .env
          echo "SWITCH_BOT_TOKEN=${{ secrets.SWITCH_BOT_TOKEN }}" >> .env
          echo "SWITCH_BOT_SECRET=${{ secrets.SWITCH_BOT_SECRET }}" >> .env
          echo "UNLOCK_BOT_ID=${{ secrets.UNLOCK_BOT_ID }}" >> .env

      - name: Build the container
        run: |
          docker-compose -f docker-compose.test.yml --env-file .env.test up -d
          docker ps

      - name: Test with pytest
        run: |
          docker-compose -f docker-compose.test.yml --env-file .env.test exec auto-unlock-server_test_1 pytest -v
          docker-compose -f docker-compose.test.yml --env-file .env.test down
